### ISSUE TITLE
w3mimgdisplay not opening images

### ISSUE THREAD

**Issue by slackhead** [autrimpo/termite#2]
I'm having problems and still can't get ranger to display images.

w3m configure options:

./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --enable-image=x11,fb \
  --enable-keymap=w3m \
  --enable-gopher \
  --with-termlib="terminfo ncurses vte-2.91" \
  --with-imagelib="gtk2 gdk-pixbuf imlib2" \
  --build=$ARCH-slackware-linux

I'm using vte3-ng 0.50.2.a

It works fine in urxvt and urxvt + screen.

Any ideas?

**Comment by autrimpo** [comment]
I've pulled the latest commit from upstream and merged it into the fork, built vte3-ng 0.50.2.a and built the newest (forked) termite with it. Everything works fine here, so can't reproduce it.

For what it's worth here's my w3m configure options:
```
--libexecdir=/usr/lib
--enable-image=x11,fb
--with-imagelib=imlib2
--with-termlib=ncurses
--disable-w3mmailer
--disable-mouse
```

Arch uses [similar](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/w3m) options, and since I haven't had any Arch users complain I assume things are working fine over there. This leads me to think it's a w3m configuration issue and I'd try playing around with the options.

Unfortunately I can't help you much beyond that, I have very little idea of how w3m actually draws the images.

**Comment by slackhead** [comment]
Could you share your vte3-ng configure options? I think that may be the problem.

Also, what is your TERM set to?

**Comment by autrimpo** [comment]
```
--prefix=/usr
--sysconfdir=/etc
--libexecdir=/usr/lib/vte
--localstatedir=/var
--disable-static
--enable-introspection
```

TERM is `xterm-termite`.

**Comment by slackhead** [comment]
Thanks. I got it working by using the w3m source that Arch is using, which comes from debian.
